### ISSUE TITLE
Use ubi8-minimal as base image for Dockerfile, and change code to use yarn for building

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-ui#15]
To be consistent with the standards within konveyor, model the Dockerfile and change code to be similar to https://github.com/konveyor/mig-ui/blob/master/Dockerfile

**Comment by parkedwards** [comment]
@ashokponkumar i'll take this one

**Comment by ashokponkumar** [comment]
sure @parkedwards . Do reach out in comments if you need more information.
