### ISSUE TITLE
Update all `npm` compile steps to yarn + remove package-lock.json

### ISSUE THREAD

**Issue by parkedwards** [konveyor/move2kube-ui#17]
It's a better practice to use either `yarn` or `npm` for dependency builds, but not both.

Requirements:
* update all `npm build` or `npm run build` steps to use `yarn`
* remove `package-lock.json` so that only `yarn.lock` remains

**Comment by parkedwards** [comment]
@ashokponkumar I can take a crack at this too while I'm at it

**Comment by ashokponkumar** [comment]
That would be great @parkedwards

**Comment by ashokponkumar** [comment]
Also, if there are any more enhancements that you believe would improve the quality of the project, please do suggest.

**Comment by HarikrishnanBalagopal** [comment]
Going with yarn because of https://github.com/konveyor/move2kube-ui/issues/15
