### ISSUE TITLE
Show default value for input question type

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-ui#29]
Show default value for input question type

**Comment by ashokponkumar** [comment]
@Akash-Nayak Isn't it better if the default value is entered directly into the text box or chosen, instead of showing it as text? Also what should be the behaviour if the value is empty? 

Also, in case of multi-choice, we need to select the default value.

**Comment by Akash-Nayak** [comment]
> @Akash-Nayak Isn't it better if the default value is entered directly into the text box or chosen, instead of showing it as text? Also what should be the behaviour if the value is empty?
> 
> Also, in case of multi-choice, we need to select the default value.

Yes definitely, it will be better if the default value is pre-entered into the text box. I think if the value is empty may be we can keep the text box empty.

**Comment by ashokponkumar** [comment]
If the value is empty if the backend is rejecting the answer, then it would be a problem. Lets check in move2kube, how it handles when the value is empty

**Comment by ashokponkumar** [comment]
We need to support this in confirm question type too.

**Comment by Akash-Nayak** [comment]
> We need to support this in confirm question type too.

Okay sure.
