### ISSUE TITLE
Collect- Move2Kube command line tool download link redirects to github.ibm.com

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube-ui#45]
In `Collect Source/Target Trtifacts`, the link to download the Move2Kube command line tool is http://ibm.biz/move2kube-release which redirects to github.ibm.com.

<img width="1328" alt="Screenshot 2020-12-22 at 2 37 32 PM" src="https://user-images.githubusercontent.com/14867323/102870820-93f9ba00-4463-11eb-9996-be0f0bf003c4.png">

**Comment by ashokponkumar** [comment]
Nice find. Let's make it redirect to koneyor.io's installation page

**Comment by Akash-Nayak** [comment]
> Nice find. Let's make it redirect to koneyor.io's installation page

Sure, I will make the changes and check in the code again.
