### ISSUE TITLE
Optimize Dockerfile

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-ui#7]
1. Optimize the Dockerfile to use a server
2. Build artifacts and host in server

**Comment by jams008** [comment]
hi, can i help with dockerfile optimization, as best i can?

**Comment by ashokponkumar** [comment]
sure @jams008

**Comment by jams008** [comment]
thank you, okay will me

**Comment by jmontleon** [comment]
You may want to look at https://github.com/konveyor/mig-ui/blob/master/Dockerfile as one example of how to build assets on a build container (which is discarded afterwards) and copy them to a runtime container using a multi-stage build.

**Comment by ashokponkumar** [comment]
Thanks @jmontleon . @jams008 Do you want to have a look at  https://github.com/konveyor/mig-ui/blob/master/Dockerfile and try it out for move2kube-ui?

**Comment by jams008** [comment]
I optimized the base image which was smaller before, up to 1GB, now it is only 300 MB, I tidy up the writing structure and I update the docker-compose file to build automatically when it's up. #14

**Comment by jams008** [comment]
Hi @ashokponkumar , I fixed it and used 'git commit -a -m' but the ci DCO still got an error.

**Comment by ashokponkumar** [comment]
@jams008 It is git commit **-s** -m message

**Comment by jams008** [comment]
yes I've used it
![Uploading image.png…]()

**Comment by ashokponkumar** [comment]
Closed by #14
