### ISSUE TITLE
Use podman as runtime to build and execute the UI

### ISSUE THREAD

**Issue by rmarting** [konveyor/move2kube-ui#97]
**Is your feature request related to a problem? Please describe.**

`docker` is currently supported to build and run locally UI, however in development environments `podman` or `buildah` are the tools used to build and run containers.

If you don't have `docker` the build process fails with:

```shell
❯ make cbuild
docker build -t quay.io/konveyor/move2kube-ui-builder:latest --cache-from quay.io/konveyor/move2kube-ui-builder:latest --target build_base                             --build-arg VERSION=latest .
make: docker: No such file or directory
make: *** [Makefile:73: cbuild] Error 127
```

**Describe the solution you'd like**

Allow to build and run locally this tool using other container runtimes, such as `podman`. 

**Describe alternatives you've considered**

**Additional context**

This feature will allow to increase the number of users/developers of this tool.

**Comment by HarikrishnanBalagopal** [comment]
@rmarting The recommended solution seems to be just to alias docker to podman since podman is a drop in replacement for docker:
```
alias docker=podman
```
https://podman.io/#what-is-podman-podman-is-a-daemonless-container-engine-for-developing-managing-and-running-oci-containers-on-your-linux-system-containers-can-either-be-run-as-root-or-in-rootless-mode-simply-put-alias-dockerpodman-more-details-here

**Comment by rmarting** [comment]
@HarikrishnanBalagopal it could help that using an alias, but IMHO the `Makefile` should cover both container technologies if we want to demostrate the value of other container runtimes such as `podman`.

Replacing `docker` references in the `Makefile` file to `podman` the build works successfully. Now it is not running because it is affected by the issue reported [here](https://github.com/konveyor/move2kube/issues/594).

Maybe the solution could add some container runtime check at the begining of the `Makefile` to avoid the developer has to use alias or change the development station to build and compile this tool. Again this mi opinion, and maybe I am wrong, and the tool has to force to use `docker` to build and run.

WDYT?

**Comment by rmarting** [comment]
@HarikrishnanBalagopal I am not an expert developer in `Makefile` files, however I created this PR #98 as an approach of my idea to use `docker` or `podman` to build and run the tool. I hope this PR could help to improve this User Experience.

Open to modify or adapt the file with the rules or recomendations you could suggest me.
